"use client";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export default function TermsOfServicePage() {
  return (
    <>
      {/* ── Sticky Header ────────────────────────────────────── */}
      <Header />

      <main className="w-full bg-[#fffff9] pt-36 pb-24 select-none">
        
        {/* ── Terms of Service Container ──────────────────────── */}
        <div className="max-w-[760px] mx-auto px-6 text-left font-primary">
          
          {/* Page Title */}
          <h1 className="font-black text-2xl sm:text-[34px] text-charcoal uppercase tracking-tight text-center mb-8">
            TERMS OF SERVICE
          </h1>

          {/* Legal Notice Banner */}
          <div className="bg-stone-50 border border-stone-200/60 rounded-2xl px-5 py-4 mb-12 text-[11px] sm:text-[12px] text-charcoal/55 font-bold leading-relaxed text-center uppercase tracking-wider">
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </div>

          {/* Content Sections */}
          <div className="flex flex-col gap-10 text-xs sm:text-[13px] text-charcoal/80 font-bold leading-relaxed">
            
            {/* Overview */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Overview</h2>
              <p>The domain name <a href="https://sustentofood.com" className="underline hover:text-black font-black">https://sustentofood.com</a> and its related sub-domains, sites, services, and tools (collectively, "Website") is owned and operated by <strong className="text-charcoal">Sustento Foods Private Limited</strong>, bearing CIN No: U10300GJ2026PTC176355 (which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to include its successors, affiliates, and permitted assigns). Throughout the Website, the terms "we", "us" and "our" refer to Sustento Foods Private Limited. We offer this Website, including all information, tools and services available from this Website to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
              <p>By visiting our Website and/or purchasing any product listed on the Website, through the Website, you engage in our services provided via the Website ("Service") and agree to be bound by the following terms and conditions ("Terms of Service"), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. You should read these Terms of Service and access and read all further linked information, if any, referred to in these Terms of Service, as such information contains further terms and conditions that apply to you as a user of the Website. Such linked information including but not limited to our privacy policy ("Privacy Policy") is hereby incorporated by reference into these Terms of Service.</p>
              <p>These Terms of Service apply to all users of the Website, including without limitation users who are browsers, customers, merchants, and/or contributors of content.</p>
              <p>Please read these Terms of Service carefully before accessing or using our Website. By accessing or using any part of the Website, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of these Terms of Service or are unable to be legally bound by these Terms of Service, then you may not access the Website or use any services or otherwise click to accept these Terms of Service, if and when prompted on the Website.</p>
              <p>Any new features or tools which are added to the Website shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on the Website. We reserve the right to update, change or replace any part of these Terms of Service at any time, and will notify you at least once in a year, or whenever there is a change in these Terms of Service, by email or by posting a conspicuous notice on the Website. Your continued use of or access to the Website following the posting of any changes constitutes acceptance of those changes.</p>
              <p>A breach or violation of any of the terms set out herein will result in an immediate termination of your access to and use of the Website and the Service.</p>
              <p>If you are unwilling or unable to be legally bound by these Terms of Service, please do not give your consent or use the Website. You cannot accept these Terms of Service if:</p>
              <p className="pl-4">(a) you are not lawfully entitled to use the Website; or</p>
              <p className="pl-4">(b) if you are not of legal age to form a binding agreement with us.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Acceptance */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Acceptance of Terms of Service</h2>
              <p>By using this Website, you agree to these Terms of Service. You&apos;re considered to have accepted them either by (a) clicking "accept" when prompted on the Website, or (b) actually using the Website. In both cases, your continued use of the Website means you understand and agree to these Terms.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* General Conditions */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">General Conditions</h2>
              <p>We may, at our discretion, refuse service to anyone at any time, for any reason.</p>
              <p>You understand that while your personal content (not including payment details) may travel across different networks unencrypted and adapt to technical requirements, your credit/debit card information is always encrypted during transfer over secure networks.</p>
              <p>You agree not to reproduce, duplicate, copy, sell, resell, or exploit any part of the Service, use of the Service, or access to the Service (or any contact provided through the Website) without our express written consent.</p>
              <p>The headings in these Terms of Service are for ease of reading only and do not limit the scope of the Terms themselves.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Accuracy */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Accuracy, Completeness and Timeliness of Information</h2>
              <p>We are not responsible if information made available on this Website is not accurate, complete or current. The material on this Website is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this Website is at your own risk.</p>
              <p>This Website may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this Website at any time, but we have no obligation to update any information on this Website. You agree that it is your responsibility to monitor changes to this Website.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Modifications */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Modifications to the Service and Prices</h2>
              <p>Prices for our products are subject to change without notice.</p>
              <p>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice.</p>
              <p>We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Products or Service */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Products or Service</h2>
              <p>Certain products or services may be available exclusively online through the Website. These products or services may have limited quantities and are subject to return or exchange only according to our Returns and Refunds Policy.</p>
              <p>We have made every effort to display as accurately as possible the colours and images of our products on the Website. We cannot guarantee that your computer monitor&apos;s display of any colour will be accurate.</p>
              <p>We reserve the right but are not obligated, to limit the sales of our products or Service to any person, geographic region or jurisdiction. We may also discontinue any or all of the products and Service provided on the Website, as we may deem fit. All descriptions of products or product pricing are subject to change at any time without notice, at our sole discretion. Any offer for any product or service made on this Website is void where prohibited.</p>
              <p>We do not warrant that the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected. Any use by you of tools offered through the Website is entirely at your own risk and discretion.</p>
              <p>The provision of Service on the Website may be interrupted, including for maintenance, repairs, upgrades, or network or equipment failures. We strive to keep the Website up and running; however, all online services suffer occasional disruptions and outages, and we are not liable for any disruption or loss you may suffer as a result.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Billing */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Accuracy of Billing and Account Information</h2>
              <p>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit/debit card, and/or orders that use the same billing and/or shipping address.</p>
              <p>You agree to provide current, complete and accurate purchase and account information for all purchases made from the Website. You agree to promptly update your account and other information, including your email address and credit/debit card numbers and expiration dates, so that we can complete your transactions and contact you as needed.</p>
              <p>For more detail, please review our Returns and Refunds Policy.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Third-Party Links */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Third-Party Links</h2>
              <p>Certain content, products and services available on our Website may include third party materials, links or interactive functionality. Any inclusion of such third party materials does not imply any sponsorship or association with the third party.</p>
              <p>Third-party links on this Website may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content, accuracy, functionality, actions, privacy settings, or policies of any such third party materials or websites.</p>
              <p>We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* User Comments */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">User Comments, Feedback and Other Submissions</h2>
              <p>If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise or post certain content, data or information belonging to you (collectively, "Comments"), you agree that we may, at any time, without restriction, edit, copy, publish, share, distribute, translate and otherwise use in any medium any Comments that you forward to us.</p>
              <p>You hereby grant us a perpetual, non-revocable, worldwide, royalty-free and sub-licensable right and license to use, copy, share, distribute, display, publish, transmit, make available, reproduce, modify, adapt the Comments and create derivative works of the Comments.</p>
              <p>You, being the originator of the Comments, are responsible for the Comments that you upload, post, publish, transmit or otherwise make available on the Website. You represent and covenant that you have obtained all relevant consents and approvals in order to post any Comments.</p>
              <p>We may, but have no obligation to, monitor, edit or remove Comments that we determine in our sole discretion are unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party&apos;s intellectual property or these Terms of Service.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Agreement to Receive Communication */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Agreement to Receive Communication</h2>
              <p>You hereby by way of accepting these Terms of Service consent to the receipt of communication from us by way of in-app messages, Short Message Service (SMS) messages, e-mails, promotional, marketing calls and newsletters. These emails could relate to your registration, transactions that you carry out through the Website and promotions that are undertaken by us, services from us and its third-party partners (if applicable).</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Personal Information */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Personal Information</h2>
              <p>Your submission of personal information through the Website is governed by our Privacy Policy. The personal information / data provided to us by you during the course of usage of the Website will be treated as strictly confidential and in accordance with the Privacy Policy and applicable laws and regulations. If you object to your information being transferred or used, please do not use the Website.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Errors */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Errors, Inaccuracies and Omissions</h2>
              <p>Occasionally there may be information on our Website or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability or even general content. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service is inaccurate at any time with prior notice.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Payment Facility */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Payment Facility</h2>
              <p>The Website permits payment via various modes, including cash on delivery (COD), virtual payment wallets and online payments through debit/credit cards and internet banking.</p>
              <p>If you purchase the products using the cash on delivery (COD) option, the orders placed will be verified before dispatch via e-mail or multimedia text messages as SMS, WhatsApp, or phone calls from us. Upon delivery of the products, you are not permitted to refuse receipt of such products.</p>
              <p>All payments made against the purchases on Website by you shall be compulsorily in Indian Rupees. It is expressly clarified that we will not facilitate transaction with respect to any other form of currency with respect to the purchases made on the Website.</p>
              <p>You acknowledge that we will not be liable for any damages, interests or claims, losses resulting from or suffered on account of not processing a transaction/transaction amount or any delay in processing a transaction/transaction amount which is beyond our control.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Content and Intellectual Property */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Content and Intellectual Property Rights</h2>
              <p>Except for Comments and any third-party intellectual property that we may use in any content on the Website, all of the content and services and products provided on the Website, including text, software, scripts, code, designs, graphics, photos and other content and the copyrights, trademarks, service marks, logos, trade names, and other intellectual and proprietary rights associated therewith ("IP") is owned by us or others that we license such content from, and is protected by copyright, trademark, patent and other intellectual property laws.</p>
              <p>Through your use of the Website, by no means are any rights impliedly or expressly granted to you in respect of such IP. You may download material from the Website only for your own personal use and for no commercial purposes whatsoever.</p>
              <p>You shall use the Website strictly in accordance with these Terms of Service, and shall not, directly or indirectly, (a) decompile, disassemble, reverse engineer, or attempt to derive the source code of, or in any manner decrypt, the Website; (b) make any modification, adaptation or improvement; (c) violate any applicable laws, rules or regulations; (d) use the Website for any commercial or revenue generation endeavors; (e) use the Website for data mining, scraping, crawling, redirecting, or for any purpose not in accordance with these Terms of Service.</p>
              <p>Any infringement shall lead to appropriate legal proceedings against you at an appropriate forum for seeking all available remedies under applicable laws of the country.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Referrals and Rewards */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Referrals and Rewards</h2>
              <p>From time to time, we may offer referral bonuses and rewards to you for inviting new users to the Website and for completing other activities. The details of such referral programs, including eligibility, benefits, limitations and reward structures, will be made available on the Website and may be updated, modified, suspended or withdrawn by us at our sole discretion.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Indemnification */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Indemnification</h2>
              <p>You agree to indemnify, defend and hold harmless Sustento Foods Private Limited and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, or actions including reasonable attorneys&apos; fees, made by any third-party or penalty imposed due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Severability */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Severability and Waiver</h2>
              <p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
              <p>The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Termination */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Termination</h2>
              <p>These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Service, or when you cease using the Website.</p>
              <p>We in our sole discretion for any reason or no reason, including if you have failed or if we suspect that you have failed, to comply with any term or provision of these Terms of Service, may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination.</p>
              <p>The disclaimer of warranties and the governing law provisions shall survive any termination of these Terms of Service.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Entire Agreement */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Entire Agreement</h2>
              <p>These Terms of Service, the Privacy Policy, other referenced material herein or on the Website and any policies or operating rules posted by us on this Website or in respect to the Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us.</p>
              <p>Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Governing Law */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Governing Law</h2>
              <p>These Terms of Service and any separate agreements whereby we provide you Service shall be governed by and construed in accordance with the laws of India. The place of jurisdiction shall exclusively be in Ajmer, Rajasthan.</p>
              <p>In the event of any dispute arising out of these Terms of Service the same shall be settled by a binding arbitration conducted by a sole arbitrator, appointed jointly by both parties and governed by the Arbitration and Conciliation Act, 1996, as amended from time to time. The venue and seat of arbitration shall be Ajmer, Rajasthan.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Assignment */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Assignment</h2>
              <p>You shall not license, sell, transfer or assign your rights, obligations, or covenants under these Terms of Service in any manner without our prior written consent. We reserve the right, at our own discretion, to freely assign and transfer the rights and obligations under these Terms of Service to any third party.</p>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* Grievance Redressal */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">Grievance Redressal Mechanism</h2>
              <p>For registering your concerns, complaint or grievances, please write to the designated officer of the Company at the address identified below in relation to any violation of these Terms of Service or the Applicable Laws.</p>
              <div className="bg-stone-50 border border-stone-200/50 rounded-2xl p-5 mt-2 flex flex-col gap-2 text-charcoal/80">
                <p><strong className="text-charcoal">Grievance Officer:</strong> Raj Kotadiya</p>
                <p><strong className="text-charcoal">Designation:</strong> Grievance Officer</p>
                <p><strong className="text-charcoal">Company:</strong> Sustento Foods Private Limited</p>
                <p><strong className="text-charcoal">Address:</strong> FF-105 Sonamahor Elevate, Opposite Gujrat CNG pump, kothariya, Rajkot - 360022, Gujarat, India</p>
                <p><strong className="text-charcoal">Email:</strong>{" "}<a href="mailto:info@sustentofood.com" className="underline hover:text-black">info@sustentofood.com</a></p>
                <p><strong className="text-charcoal">Phone:</strong>{" "}<a href="tel:+919924594414" className="hover:text-black">+91 99245 94414</a></p>
                <p><strong className="text-charcoal">Time:</strong> Mon – Fri (11:00 – 18:00)</p>
              </div>
            </div>

            <div className="w-full border-t border-black/5" />

            {/* How to Contact Us */}
            <div className="flex flex-col gap-3">
              <h2 className="text-charcoal font-black text-base sm:text-[17px] uppercase tracking-tight">How to Contact Us</h2>
              <p>
                Questions about these Terms of Service should be sent to us at{" "}
                <a href="mailto:info@sustentofood.com" className="underline hover:text-black font-black">
                  info@sustentofood.com
                </a>.
              </p>
            </div>

          </div>
        </div>
      </main>

      {/* ── Floating Ask Everaw Chat Widget ─────────────────── */}
      <div className="fixed bottom-6 left-6 z-50">
        <button className="bg-[#9EAB75] text-dark font-primary text-[13px] font-black uppercase tracking-wider px-4 py-2.5 rounded-full shadow-lg border border-black/10 flex items-center gap-2 hover:scale-105 active:scale-95 transition-transform duration-150">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-dark">
            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
          </svg>
          Ask Sustento
        </button>
      </div>

      {/* ── Footer ───────────────────────────────────────────── */}
      <Footer />
    </>
  );
}

